= Getting Started with ARM
:keywords: cloudhub, connectors, arm, runtime manager


Anypoint Runtime Manager provides a unified interface to manage integration applications, servers, server groups and clusters. It allows you to deploy sophisticated cross-cloud integration applications in the cloud and on premises to servers, groups of servers, and clusters. You can create new APIs on top of existing data sources, integrate on-premises applications with cloud services, manage servers and server groups on premises, and much more. With link:/mule-fundamentals/v/3.7/download-and-launch-anypoint-studio[Anypoint Studio] – the user-friendly development tool – you can quickly build integration applications and deploy to the cloud with just a few clicks; you can then manage your applications and servers via ARM.

ARM is fully integrated with CloudHub, the Anypoint Integration Platform as a Service (iPaaS) solution from MuleSoft. CloudHub is a multi-tenanted cloud platform service running on Mule, the core runtime for the Anypoint Platform. This guide helps you learn the basics, and get started developing your first application for deploying to CloudHub.

== Deploying to CloudHub: The Basics

* Use Anypoint Studio to quickly and easily design your integration application
* Deploy your application to CloudHub, the

. Download link:https://www.mulesoft.com/lp/dl/studio[Anypoint Studio].
. Read our link:/cloudhub/cloudhub-at-a-glance[CloudHub at a Glance] guide to learn the basic concepts.
. Follow our easy link:/cloudhub/hello-world-on-cloudhub[Hello World on CloudHub] tutorial to get your first integration application up and running with Anypoint Studio and CloudHub.
. link:/cloudhub/getting-started-with-connectors[Get started with connectors] to connect to external services like Twitter.
. Ready to deploy an application? See link:/cloudhub/deploying-an-application-to-arm[Deploying an Application to ARM].

Still don't understand how CloudHub can be of use to you? Read more about link:http://www.mulesoft.com/cloudhub/ipaas-cloud-based-integration-demand[things you can do with CloudHub].

== Build CloudHub Applications

Follow one of our tutorials to learn how to build CloudHub applications.

* link:/cloudhub/building-an-https-service[Building an HTTPS Service on CloudHub]
* link:/cloudhub/custom-application-alerts[Custom Application Alerts]

Want to learn more? Check out all the examples in link:/mule-fundamentals/v/3.7/anypoint-exchange[Anypoint Exchange].

== Deploy Applications to the Cloud or On Premises

The Anypoint Management Center enables you to:

* link:/cloudhub/deploying-an-application-to-arm[Deploying an Application to ARM]
* link:/cloudhub/managing-applications-in-the-cloud-and-on-premises[Manage applications and servers running on premises] from the cloud
* link:/cloudhub/creating-and-managing-clusters[Create and manage clusters] from the cloud

== Build Connectors

Are you interested in building your own connector? Use the link:/anypoint-connector-devkit/v/3.7/[Anypoint Connector DevKit] to rapidly build connectors and drop them inside of Studio.

== Other Resources

* link:/cloudhub/managing-applications-on-arm[Managing Applications on ARM]
* link:/cloudhub/reference-materials[Reference Materials]
* link:/cloudhub/community-and-support[Community and Support]
* There are tons of APIs available. Check our MuleSoft Blog to see a link:
http://blogs.mulesoft.org/top-10-weird-apis/[TOP 10 of the weirdest APIs] out there.
