= Introducing Anypoint Runtime Manager
:keywords: cloudhub, cloud, saas, applications, servers, clusters, sdg, arm, runtime manager

== Overview

=== The Anypoint Platform Interface

The Anypoint Platform Web interface allows you to manage your APIs, runtimes and integration applications from a single control point. From here you can access Anypoint Runtime Manager, Anypoint API Manager and Analytics. Together, these tools allow you to manage runtimes regardless of where they are deployed -- whether on-premises or in the cloud, or as an API gateway -- as well as deploy/undeploy applications, administer servers, view analytics data and more.

=== Anypoint Runtime Manager (ARM)

Anypoint Runtime Manager allows you to integrate and manage applications and servers, whether on-premises or in the cloud. ARM lets you integrate SaaS applications, Cloud services, and Enterprise applications in real time. It provides a simple, intuitive graphical interface to interoperate with CloudHub, the world's first integration Platform as a Service (iPaaS), the engine for your Mule applications deployed to the cloud. CloudHub itself is built on top of Mule, the most widely used integration platform. Together with Anypoint Studio, ARM and CloudHub allow you to design, run, deploy and manage your integration application, as well as the servers, clusters and groups of your environment.

== Why ARM?

=== ARM + CloudHub: Start Small, Think Big

ARM gives you the ability to deploy and manage servers and applications on-premise or in the cloud with just a few clicks. CloudHub, the platform where applications run, is an elastic cloud that scales on demand. You can start small and grow as your needs grow, all without changing your application. CloudHub provides you with a scalable architecture – one you can build integration applications on, publish REST APIs or Web Services, and much more. Using the Runtime Manager, you can also manage servers in your organization and organize servers into groups that run an application.

=== Rock Solid Platform

Built on our battle-tested Mule integration platform, Mule ESB is used by thousands of companies for mission-critical applications. It's the world's most widely used platform for integration.

=== Integrate Cloud and Enterprise Applications

The Virtual Private Cloud (VPC) feature provides a secure pipe to the enterprise, breaking down the "cloud silo." CloudHub allows you to integrate and orchestrate applications, data sources, and services across the enterprise and cloud.

=== Unrivaled Connectivity

Easily integrate with popular SaaS, cloud, and social media platforms such as Salesforce.com, Intuit, Authorize.net, Amazon, Twitter, Facebook, and PayPal using our predefined connectors – then orchestrate data between these services and the enterprise. Plus, our development kit allows developers to create new connectors easily. You don't even need knowledge of the underlying integration infrastructure.

=== Don't Change the Way You Code

Create cloud applications with the development tools you are already familiar with. Download link:https://www.mulesoft.com/ty/dl/studio[Anypoint Studio], it's free! Anypoint Studio is an Eclipse-based graphical environment that allows developers to easily choose to code in a visual environment with a palette of components, or in a familiar XML code view. You can even switch between the visual and code views as you build your application. Or, if you would rather use the command-line, we support Maven, as well as a command line tool.

=== Visibility and Control with the Anypoint Runtime Manager

Anypoint Runtime Manager provides an intuitive console where you can manage your applications and servers, scale up and scale down, view event traffic, and much more -- you can manage every aspect of your applications from one place. In addition, with link:/cloudhub/managing-servers-on-premises[application and server management] and link:/mule-user-guide/v/3.7/Creating-and-Managing-Clusters[cluster management] you can manage your on-premise servers, server groups, and clusters, plus applications from your Runtime console, giving you a single management pane of glass for all your applications and servers.

=== Behind a Great Platform is a Great API

Do you need to automate tasks, or build Runtime Manager into your deployment process? ARM has a link:/cloudhub/cloudhub-api[REST API] with which you can perform tasks such as manage and monitor your applications, scale your applications up or down, and more.
